# tap "homebrew/bundle"
# tap "homebrew/services"
tap "redpanda-data/tap"

brew "hurl"
brew "act"
brew "asdf"
brew "autoconf"
brew "automake"
brew "bat"
brew "direnv"
brew "docker"
brew "eza"
brew "fzf"
brew "gh"
brew "git"
brew "handbrake"
brew "htop"
brew "httpie"
brew "jq"
brew "just"
brew "lazydocker"
brew "lazygit"
brew "libtool"
brew "neovim"
# brew "lazyvim"
brew "ollama"
brew "postgresql@17", restart_service: :changed, link: true
brew "ripgrep"
brew "rustup"
brew "shellcheck"
brew "stow"
brew "tldr"
brew "uv"
brew "watch"
brew "z"
cask "alfred"
cask "chromedriver"
cask "claude"
cask "clipy"
cask "discord"
cask "firefox"
cask "google-chrome"
cask "handbrake-app"
cask "rectangle"
cask "slack"
cask "spotify"
cask "the-unarchiver"
cask "vlc"
cask "zed"
# brew "font-server-mono"
# brew "font-departure-mono"
brew "pgcli"
brew "llm"
# brew "cursor"
brew "helix"
brew "action-validator"
# brew "terraform"
# brew "1password-cli"
brew "git-delta"
brew "ast-grep"
brew "opencode"
brew "mise"
cask "codex"
